package com.findu.model;
// Generated 2016-3-12 23:27:55 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TGenealogyMapId generated by hbm2java
 */
@Embeddable
public class TGenealogyMapId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3592864474108167562L;
	/**用户id，针对于私有家谱*/
	private long userId = 0;
	/**家谱id*/
	private long genealogyId = 0;

	public TGenealogyMapId() {
	}

	public TGenealogyMapId(long userId, long genealogyId) {
		this.userId = userId;
		this.genealogyId = genealogyId;
	}

	@Column(name = "userId", nullable = false)
	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	@Column(name = "genealogyId", nullable = false)
	public long getGenealogyId() {
		return this.genealogyId;
	}

	public void setGenealogyId(long genealogyId) {
		this.genealogyId = genealogyId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TGenealogyMapId))
			return false;
		TGenealogyMapId castOther = (TGenealogyMapId) other;

		return (this.getUserId() == castOther.getUserId()) && (this.getGenealogyId() == castOther.getGenealogyId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUserId();
		result = 37 * result + (int) this.getGenealogyId();
		return result;
	}

}
