package com.findu.model;
// Generated 2016-3-17 9:27:25 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.TableGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * 话题表，实现家咨询、时光轴等图文混排信息发布功能的顶层实体，可以关联到用户、家谱等实体，且支持分级。
 * TTopic00 generated by hbm2java
 */
@Entity
@Cacheable
@Cache(usage=CacheConcurrencyStrategy.READ_WRITE) 
@Table(name = "t_topic")
public class TTopic implements java.io.Serializable {
	
	/**
	 * 家咨询
	 */
	public static final int TYPE_FAMILY_INFO = 1;
	/**
	 * 时光轴
	 */
	public static final int TYPE_USER_SPACE = 2;

	/**
	 * 
	 */
	private static final long serialVersionUID = 2148575127043407614L;
	
	private long topicId = 0;
	/**关联实体id，如家谱id或用户id，根据类型确定*/
	private long refId = 0;
	/**实体分表id*/
	private Long refTableSeq = null;
	/**主题模块类型，1家资讯，2时光轴*/
	private int type = 0;
	/**上级主题模块*/
	private Long superiorId = null;
	/**标题*/
	private String title = null;
	
	private Date createTime = null;

	public TTopic() {
		
	}

	public TTopic(long topicId, long refId, int type, Date createTime) {
		this.topicId = topicId;
		this.refId = refId;
		this.type = type;
		this.createTime = createTime;
	}

	public TTopic(long topicId, long refId, Long refTableSeq, int type, Long superiorId, String title, Date createTime) {
		this.topicId = topicId;
		this.refId = refId;
		this.refTableSeq = refTableSeq;
		this.type = type;
		this.superiorId = superiorId;
		this.title = title;
		this.createTime = createTime;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.TABLE, generator="customer_gen")
	@TableGenerator(name = "customer_gen",
				    table="t_seqno",
				    pkColumnName="tablename",
				    valueColumnName="seqno",
				    pkColumnValue="t_topic",
				    allocationSize=1)
	@Column(name = "id", unique = true, nullable = false)
	public long getTopicId() {
		return topicId;
	}

	public void setTopicId(long topicId) {
		this.topicId = topicId;
	}

	/**
	 * 关联实体id，如用户id或家谱id等。
	 * @return 关联实体id。
	 */
	@Column(name = "refId", nullable = false)
	public long getRefId() {
		return this.refId;
	}

	public void setRefId(long refId) {
		this.refId = refId;
	}
	
	/**
	 * 关联实体分表id字段值，为空表示关联实体不分表。
	 * @return
	 */
	@Column(name = "refTableSeq")
	public Long getRefTableSeq() {
		return refTableSeq;
	}

	public void setRefTableSeq(Long refTableSeq) {
		this.refTableSeq = refTableSeq;
	}

	/**
	 * 关联实体类型。
	 * @return 关联实体类型，1 家资讯，2 时光轴。
	 */
	@Column(name = "type", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "superiorId")
	public Long getSuperiorId() {
		return this.superiorId;
	}

	public void setSuperiorId(Long superiorId) {
		this.superiorId = superiorId;
	}

	@Column(name = "title", length = 100)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
